site_name: "netseer"

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - References: references.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  font:
    text: Lexend
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  palette:
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings
